import { getRandomNumber } from "../get-random-number";

export const hinglishAdjectives = [
    'thanda',
    'sundar',
    'saaf',
    'awesome',
    'khush',
    'chill',
    'cold',
    'tez',
    'gold',
    'bold',
    'common',
    'mast',
    'normal',
    'sahi',
    'achha',
    'bada',
    'good',
    'happy',
    'band',
    'jaldi',
    'zara',
    'best',
    'free',
    'bohot',
    'last',
    'great',
    'paas',
    'galat',
    'cute',
    'clean',
    'done',
    'only',
    'close',
    'sweet',
    'okay',
    'super',
    'pure',
    'live',
    'cool',
    'nice',
    'rich',
    'first',
    'full',
    'garam',
    'long',
    'zyada',
    'some',
    'soon',
    'epic',
    'angry',
    'faltu',
    'kind',
    'pehla',
    'bhala',
    'pakka',
    'calm',
    'daily',
    'upar',
    'high',
    'clear',
    'safe',
    'easy',
    'final',
    'heavy',
];

export async function getRandomAdjective() {
    const index = await getRandomNumber({ min: 0, max: hinglishAdjectives.length -1 });
    return hinglishAdjectives[index];
}